language: cpp
dist: xenial
before_install:
- eval "${COMPILE}"

jobs:
  include:
  - addons:
      apt:
        packages:
        - g++-4.8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=gcc-4.8 CXX=g++-4.8"
  - addons:
      apt:
        packages:
        - g++-4.8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=gcc-4.8 CXX=g++-4.8"
  - addons:
      apt:
        packages:
        - g++-4.8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=gcc-4.8 CXX=g++-4.8"
  - addons:
      apt:
        packages:
        - g++-4.9
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=gcc-4.9 CXX=g++-4.9"
  - addons:
      apt:
        packages:
        - g++-4.9
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=gcc-4.9 CXX=g++-4.9"
  - addons:
      apt:
        packages:
        - g++-4.9
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=gcc-4.9 CXX=g++-4.9"
  - addons:
      apt:
        packages:
        - g++-5
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=gcc-5 CXX=g++-5"
  - addons:
      apt:
        packages:
        - g++-5
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=gcc-5 CXX=g++-5"
  - addons:
      apt:
        packages:
        - g++-5
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=gcc-5 CXX=g++-5"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=gcc-6 CXX=g++-6"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=gcc-6 CXX=g++-6"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=gcc-6 CXX=g++-6"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=gcc-7 CXX=g++-7"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=gcc-7 CXX=g++-7"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=gcc-7 CXX=g++-7"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=gcc-8 CXX=g++-8"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=gcc-8 CXX=g++-8"
  - addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=gcc-8 CXX=g++-8"
  - addons:
      apt:
        packages:
        - clang-3.5
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=clang-3.5 CXX=clang++-3.5"
  - addons:
      apt:
        packages:
        - clang-3.5
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=clang-3.5 CXX=clang++-3.5"
  - addons:
      apt:
        packages:
        - clang-3.5
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=clang-3.5 CXX=clang++-3.5"
  - addons:
      apt:
        packages:
        - clang-3.6
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=clang-3.6 CXX=clang++-3.6"
  - addons:
      apt:
        packages:
        - clang-3.6
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=clang-3.6 CXX=clang++-3.6"
  - addons:
      apt:
        packages:
        - clang-3.6
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=clang-3.6 CXX=clang++-3.6"
  - addons:
      apt:
        packages:
        - clang-3.8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=clang-3.8 CXX=clang++-3.8"
  - addons:
      apt:
        packages:
        - clang-3.8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=clang-3.8 CXX=clang++-3.8"
  - addons:
      apt:
        packages:
        - clang-3.8
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=clang-3.8 CXX=clang++-3.8"
  - addons:
      apt:
        packages:
        - clang-3.9
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=clang-3.9 CXX=clang++-3.9"
  - addons:
      apt:
        packages:
        - clang-3.9
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=clang-3.9 CXX=clang++-3.9"
  - addons:
      apt:
        packages:
        - clang-4.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=clang-4.0 CXX=clang++-4.0"
  - addons:
      apt:
        packages:
        - clang-4.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=clang-4.0 CXX=clang++-4.0"
  - addons:
      apt:
        packages:
        - clang-4.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=clang-4.0 CXX=clang++-4.0"
  - addons:
      apt:
        packages:
        - clang-5.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=clang-5.0 CXX=clang++-5.0"
  - addons:
      apt:
        packages:
        - clang-5.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=clang-5.0 CXX=clang++-5.0"
  - addons:
      apt:
        packages:
        - clang-5.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=clang-5.0 CXX=clang++-5.0"
  - addons:
      apt:
        packages:
        - clang-6.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Debug COMPILE="CC=clang-6.0 CXX=clang++-6.0"
  - addons:
      apt:
        packages:
        - clang-6.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=Release COMPILE="CC=clang-6.0 CXX=clang++-6.0"
  - addons:
      apt:
        packages:
        - clang-6.0
        - libjson-c-dev
        - libssl-dev
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="CC=clang-6.0 CXX=clang++-6.0"

  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=Debug COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=Release COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode10.3
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=Debug COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode10.3
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=Release COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode10.3
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode11.3
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=Debug COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode11.3
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=Release COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode11.3
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode11.6
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=Debug COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode11.6
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=Release COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  - os: osx
    osx_image: xcode11.6
    addons:
      homebrew:
        packages:
        - openssl
        - json-c
        update: true
    env:
    - BUILD_TYPE=RelWithDebInfo COMPILE="OPENSSL_ROOT_DIR=/usr/local/opt/openssl"

# Change this to your needs
script:  cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR} && make VERBOSE=1 -j 4
