/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_choury_sproxy_SproxyVpnService */

#ifndef _Included_com_choury_sproxy_Service
#define _Included_com_choury_sproxy_Service
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_choury_sproxy_SproxyVpnService
 * Method:    start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_choury_sproxy_SproxyVpnService_start(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
