/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_choury_sproxy_SproxyVpnService */

#ifndef _Included_com_choury_sproxy_Service
#define _Included_com_choury_sproxy_Service
#ifdef __cplusplus
extern "C" {
#endif

extern char version[];

/*
 * Class:     com_choury_sproxy_SproxyVpnService
 * Method:    start
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_choury_sproxy_SproxyVpnService_start(JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_choury_sproxy_SproxyVpnService
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_choury_sproxy_SproxyVpnService_stop(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_choury_sproxy_SproxyVpnService_reset(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_choury_sproxy_SproxyVpnService_reload(JNIEnv *, jobject);


void android_log(int level, const char* fmt, ...);
const char* getPackageName(int uid);
const char *getDeviceName();
#ifdef __cplusplus
}
#endif
#endif
